### PR TITLE
Maintain Directory Structure during clone

### PR DESCRIPTION
**Pull request by prabhat625**
### Summary
Created a function to create a nesting directory.

### Clubhouse Ticet
<a href="https://app.clubhouse.io/jovian/story/2435/maintain-directory-structure-upon-clone"> Ticket </a>

### Result
result
result

### CODE REVIEW

**Comment by PrajwalPrashanth** [comment]
@prabhat625 some test cases are failing. Please check them out

**Comment by prabhat625** [comment]
@PrajwalPrashanth  Now All test cases are passed.
Problem:- Our testing files don't have 'folder' key. 
Solution:- Instead f['folder'] we can use f.get('folder)

**Comment by aakashns** [comment]
@PrajwalPrashanth please review the updated PR

**Comment by aakashns** [comment]
Thanks for taking this up. However, the implementation can be simplified significantly. I've done it in #232 , so closing this for now.

**Pull request closed without merging**
