### PR TITLE
Bz/lab ext module 1 to 3

### PR DESCRIPTION
**Pull request by bendesu**
##The lab ext. source code with both internal and external doc.

### The Jovian extension icon:

buttons

### The Dropdown menu:

Dorpdown

### The Parameter window:

parameter

### The API window:

API window

### The Commit window:

Commit window

### The Settings window:

settings

### CODE REVIEW

**Comment by bendesu** [comment]
sidebar
sidebar err

**Comment by bendesu** [comment]
The latest version of the lab extension is built for JupyterLab version 2.0 at least. Since JupyterLab upgraded from 1.0 to 2.0, they changed a lot of API from their library. Thus, when you wanna use this extension, make sure you have JupyterLab 2.0 at least.

**Comment by aakashns** [comment]
This is looking great! Nice work @bendesu! Looking forward to deploying and using this soon.

**Comment by PrajwalPrashanth** [comment]
Closing this PR. Since the changes are included in #159 and #161.

**Pull request closed without merging**
